# Generated by Django 5.0.7 on 2024-07-10 23:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notesapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Notes",
            new_name="Note",
        ),
    ]
