# Generated by Django 5.0.7 on 2024-07-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notesapp", "0002_rename_notes_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
