# Generated by Django 5.0.7 on 2024-07-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notesapp", "0003_alter_note_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="category",
            field=models.CharField(
                choices=[
                    ("BUSINESS", "Business"),
                    ("PERSONAL", "Personal"),
                    ("IMPORTANT", "Important"),
                ],
                default="PERSONAL",
                max_length=15,
            ),
        ),
    ]
